spring:
  application:
    name: floppy
  datasource:
    url: jdbc:h2:file:./floppy.db
    driverClassName: org.h2.Driver
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true

floppy:
  bot:
    token:
      telegram: ${FLOPPY_BOT_TOKEN_TG}
