spring:
  application:
    name: floppy
  datasource:
    url: jdbc:h2:file:./spring-boot-h2-db
    driverClassName: org.h2.Driver
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

floppy:
  bot:
    token: ${FLOPPY_BOT_TOKEN}
